### ISSUE TITLE
Decimal points not sent  [Bug]

### ISSUE THREAD

**Issue by boundlessmaking** [RobotExMachina/Machina-Bridge#3] opened 2019-04-25 13:40 UTC
Hello, First of all, thank you for this software. 
However I have a problem that makes it unusable: **the decimal points are not sent to the robot**
This is obvious looking at this image: 
![decimals not sent](https://i.imgur.com/6L7C18q.png)
As you can see the move command specifies a move towards positive z by 1.01mm (Line 1)
What is sent instead is a move of 101mm in z direction (Line 4) and the robot moves accordingly. 
If there is no decimal point (for example: Move(0,0,1)) the robot moves correctly. 
This happens with both v_0.8.8 and v_0.8.6 of machina-bridge.

What is going on here? is the problem on my side or a problem with bridge or the machina framework in general ? 

I am running machina on native windows (bootcamp on a macbook pro) and sending commands to a UR5 Universal robot. 

Would love to have a solution to this so I can start using the program to its full capacity.
Thanks in advance 
Greetings 
Robin

**Comment by garciadelcastillo** [comment] 2019-04-26 17:52
Interesting, this very much looks like an issue with `locales` that I thought I solved with [0.8.4](https://github.com/RobotExMachina/Machina.NET/releases/tag/v0.8.4). 

Can you please answer these?
- Can you describe the simplest workflow/set of actions that lead to this problem? I would like to try to reproduce it.
- Do whole mm units work otherwise? Can you send a `Move(0, 0, 100);` and have it work correctly? 
- What is your `Culture`? This means, which country are you based, what regional configuration is your OS configured for, and what is your OS language? Regional difference on how decimal numbers are noted has caused stringification problems in the past (which again, I thought I had solved... :(

Thanks!

**Comment by boundlessmaking** [comment] 2019-04-27 12:11
> * Can you describe the simplest workflow/set of actions that lead to this problem? I would like to try to reproduce it.

What I described is the simplest set of actions (sending "move(0,0,1.01)") to reproduce this. I first sent commands via grasshopper and the same thing happened, and I thought it was a problem with grasshopper /rhino messing up decimals or units. Only later I realised the same thing happens when I send commands directly from bridge.

> * Do whole mm units work otherwise? Can you send a `Move(0, 0, 100);` and have it work correctly?

Yes this works correctly 

> * What is your `Culture`? This means, which country are you based, what regional configuration is your OS configured for, and what is your OS language? 

I am in Germany, my OS (Windows 10)

display language: English (germany)
country or region: Germany
Regional format: English (Germany)

Should I try to change these settings to see if it makes a difference ? 
I only have access to the robot in a week, is there a way to test this without the robot ?

**Comment by garciadelcastillo** [comment] 2019-04-27 14:02
Yes, if you could try setting everything to USA English and running it again it would be very helpful. What you are describing was a known problem that I thought I solved, but there might be some small corner case out there that I missed. 

If you don't have a physical UR available to try, you can always set up a RobotStudio simulation and try your workflows there. Take a look at the [Robot Setup Tutorials](https://www.youtube.com/playlist?list=PLvxxYImPCApUffcv_KtdR-sQydA4O4CPH) for instructions on how to do that. 

Let me take a look at this today.

**Comment by garciadelcastillo** [comment] 2019-04-27 16:55
I found the problem: I had fixed `Culture`-related parsing problems at the Machina core, but there was some number parsing happening on the Bridge that was not accounting for these differences. 

I have pushed a new release with the fix: [v0.8.8b](https://github.com/RobotExMachina/Machina-Bridge/releases/tag/v0.8.8b). Can you please let me know if this is fixed and we can close the issue?

Thanks for reporting, and let me know if you do something cool :)

**Comment by boundlessmaking** [comment] 2019-04-27 17:39
I just tested it with abb robot studio, without changing my regional settings. 
It works as it should! Thank you very much.

What it does in v_0.8.8:
<img width="338" alt="0 8 8" src="https://user-images.githubusercontent.com/25942644/56853139-054a3800-6924-11e9-91d8-4ed00d4ae345.PNG">
notice how the move of -1.01 in z results in a target position that is -101 of the previous 

What it does in v_0.8.8b:

<img width="344" alt="0 8 8b" src="https://user-images.githubusercontent.com/25942644/56853141-0a0eec00-6924-11e9-8f37-cf699c3d529c.PNG">
the move is now done correctly

**Comment by garciadelcastillo** [comment] 2019-04-27 17:51
Wonderful.

**Closed by garciadelcastillo** 2019-04-27 17:51 UTC
Labels: bug
